### ISSUE TITLE
Add solution

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-reference-types-practice#12]
Or solutions?

**Comment by jrhorn424** [comment]
I have a question for your question. What sort of feedback are you looking for?

**Comment by gaand** [comment]
@jrhorn424 It's the challenge versus thing. Does it matter if developers have access to solutions in the challenge/practice?

**Comment by gaand** [comment]
More, should we show several different options accomplishing the same results?

**Comment by RealWeeks** [comment]
Two students have written additional tests for the bonus question.  Pending your decision they can be added, both are still open pull request with the label "enhancement".

**Comment by jrhorn424** [comment]
Since this has become a practice, I think it should have an example solution.

**Comment by jrhorn424** [comment]
I see that a solution is present. Can we close this @gaand?

**Comment by gaand** [comment]
Yes.
