### ISSUE TITLE
Discussion of scope?

### ISSUE THREAD

**Issue by benjimelito** [ga-wdi-boston/js-reference-types-practice#121]
I noticed that a large number of developers seems to be creating global variables for this practice, rather than placing them inside their functions. I wonder if a discussion about scope would be appropriate at this point?

**Comment by gaand** [comment]
@benjimelito Technically, they're not global, but I understand what you mean.

I think for this practice it's fine that they put the variables wherever makes sense to them.  If they actually ended up in the global scope I might feel differently.  Please close this.
